spring.application.name=mmas

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/mmas?sslmode=disable
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
voice.storage.path=classpath:voice_uploads

# WebAuthn (example)
webauthn.rp-id=localhost
webauthn.rp-name=MMAS
webauthn.allowed-origins=http://localhost:8080

# VOSK
vosk.model.path=classpath:vosk-model-small-en-us-0.15
vosk.spk.model.path=classpath:vosk-model-spk-0.4
